services:
  api-documentation-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      SPRING_PROFILES_ACTIVE: production
    restart: always